baseURL = 'http://markarydsvarmarknad.se/'
languageCode = 'en-us'
title = ' '
theme =  "PaperMod"
enableInlineShortcodes = true

[params]
ShowShareButtons = false
ShareButtons = [ "Linkedin", "Instagram", "facebook" ]
defaultTheme = "dark"
label.icon = "marre.svg"



[[menu.main]]
  identifier = 'Sponsorer'
  name = 'Sponsorer'
  url = '/Sponsorer/'
  weight = 20

[[menu.main]]
  identifier = 'Agenda'
  name = 'Agenda'
  url = '/Agenda/'
  weight = 30


  [[menu.main]]
  identifier = 'Kontakta oss'
  name = 'Kontakta oss'
  url = '/Kontakta-oss/'
  weight = 40

    [[menu.main]]
  identifier = 'Bildgalleri'
  name = 'Bildgalleri'
  url = '/Bildgalleri/'
  weight = 50


